apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: velflix-nginx
  name: velflix-nginx
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 32000
  selector:
    app: velflix-nginx
  type: NodePort
