apiVersion: apps/v1
kind: Deployment

metadata:
  creationTimestamp: null
  labels:
    app: velflix-fpm
  name: velflix-fpm
spec:
  selector:
    matchLabels:
      app: velflix-fpm
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: velflix-fpm
    spec:
      containers:
      - image: mahdi0188/velflix-fpm:dev-18-05f05ee
        name: velflix-fpm
        resources:
          limits:
            cpu: 150m
          requests:
            cpu: 100m
status: {}
