apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: velflix-nginx
  name: velflix-nginx
 
spec:
  selector:
    matchLabels:
      app: velflix-nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: velflix-nginx
    spec:
      containers:
      - image: mahdi0188/velflix-nginx
        name: velflix-nginx
        resources:
          limits:
            cpu: 150m
          requests:
            cpu: 100m
status: {}
